server:
  port: 8081
spring:
  application:
    name: zsxy
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dianping?useSSL=false&serverTimezone=UTC
    username: root
    password: gaiwangle
  redis:
    host: //***
    port: 6379
    password: 123321
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  servlet:
    multipart:
      max-file-size: 20MB
mybatis-plus:
  type-aliases-package: com.zsxy.entity # 别名扫描包
logging:
  level:
    com.zsxy: debug
